name: Publish Ruby Gem

on:
  push:
    branches: [release/*]
  workflow_run:
    workflows: ["Testing"]
    branches: [release/*]
    types:
      - completed

jobs:
  publish-rubygem:
    name: Publish Ruby Gem
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - run: echo "Hello world!"
