name: Publish Ruby Gem

on:
  release:
    types: [published]

jobs:
  publish-rubygem:
    name: Publish Ruby Gem
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - run: echo "Hello world!"
