name: Publish Ruby Gem

on:
  push:
    branches: [release/*]

jobs:
  publish-rubygem:
    name: Publish Ruby Gem
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --quiet origin main
          git merge-base --is-ancestor HEAD origin/main
      - run: echo "Hello world!"
