# Makes an automated release
#
# To trigger this workflow, ensure the CHANGELOG is up to date, then push the commit
# to be released to a `release/*` branch.
#
# e.g.
#     git push main:release/vX.Y.X
#
name: Release

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/action-create-github-release@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}