# Makes an automated release
#
# To trigger this workflow, ensure the CHANGELOG is up to date, then push the commit
# to be released to a `release/*` branch.
#
# e.g.
#     git checkout -b release/v1.0.0
#     git push
#
name: Release

on:
  workflow_run:
    workflows: ["Testing"]
    branches: [release/*]
    types:
      - completed

jobs:
  read-version:
    name: Read version to release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versions.outputs.changelog-latest-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/action-get-versions@v1.0.0
        id: versions

  publish-go:
    name: Create go/* tag
    runs-on: ubuntu-latest
    needs: read-version
    steps:
      - uses: actions/checkout@v2
      - name: Create git tag
        run: |
          git tag "go/test-v${{ needs.read-version.outputs.version }}"
          git push --tags
