name: Test

on:
  push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          [[ true == true ]] # change this to `true == false` to make the tests fail
